[package]
name = "sherpa-rs"
version = "0.1.1"
edition = "2021"
authors = ["thewh1teagle"]
license = "MIT"
repository = "https://github.com/thewh1teagle/sherpa-rs"
description = "Rust bindings to https://github.com/k2-fsa/sherpa-onnx"
readme = "README.md"
keywords = [
    "audio",
    "embeddings",
    "speech-recognition",
    "sherpa",
    "diarization",
]

[dependencies]
eyre = "0.6.12"
hound = "3.5.1"
log = "0.4.22"
sherpa-rs-sys = { path = "sys", version = "0.1.0" }
env_logger = { version = "0.11.3", features = ["color"] }

[workspace]
members = ["sys"]
