[package]
name = "sherpa-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.12"
hound = "3.5.1"
log = "0.4.22"
sherpa-rs-sys = { path = "sys", version = "0.1.0" }

[workspace]
members = ["sys"]
