[package]
name = "sherpa-rs"
version = "0.1.0"
edition = "2021"
authors = ["thewh1teagle"]
repository = "https://github.com/thewh1teagle/sherpa-rs"

[dependencies]
eyre = "0.6.12"
hound = "3.5.1"
log = "0.4.22"
sherpa-rs-sys = { path = "sys", version = "0.1.0" }

[build-dependencies]
nalgebra = "0.33.0"

[workspace]
members = ["sys"]
