name: Publish Crate

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Publish the sys crate
      - name: Publish sys crate
        uses: katyo/publish-crates@v2
        with:
          args: -p sherpa-rs-sys
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # Publish the main crate
      - name: Publish main crate
        uses: katyo/publish-crates@v2
        with:
          args: -p sherpa-rs
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
